include:
  - ./api/compose.yml
  - ./caddy/compose.yml
  - ./keycloak/compose.prod.yml
  - ./ui/compose.yml
  
services:
  keycloak:
    networks:
      - proxy_net
  api:
    networks:
      - proxy_net
  ui:
    networks:
      - proxy_net
    
networks:
  proxy_net:
    driver: bridge
  