services:
  ui:
    image: ghcr.io/mrzjkl/fireinvent-ui:ghcr.io-mrzjkl-fireinventui-latest 
    container_name: fireinvent_ui
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      VITE_KEYCLOAK_URL: ${VITE_KEYCLOAK_URL}
      VITE_KEYCLOAK_REALM: ${VITE_KEYCLOAK_REALM:-fireinvent}
      VITE_KEYCLOAK_CLIENT_ID: ${VITE_KEYCLOAK_CLIENT_ID:-fireinvent-spa}